### ISSUE TITLE
Movie Show: Reviews - <em> tags showing in review descriptions

### ISSUE THREAD

**Issue by helloeduardo** [ETBassist/viewing_party#25]
When running `save_and_open_page` in the `show_spec.rb` for movies, it displays `<em>` tags.

To do:
  - Investigate the API response and see if there is a way to remove those tags or convert them to html.

**Comment by ETBassist** [comment]
Putting [this](https://stackoverflow.com/questions/4576932/ruby-on-rails-how-to-render-a-string-as-html) here for future reference

**Comment by ETBassist** [comment]
`simple_format` may also fit the bill https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-simple_format
